name: balaiku_app
description: "Aplikasi Mobile Layanan Desa BalaiKu"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  path: ^1.9.1
  sqflite: ^2.4.2+1

flutter:
  uses-material-design: true
  assets:
    - assets/images/